Repository jesp1999/heckbot, pull requests merged in 2023-02, with the labels that each got.

#51 Add dpytest int testing
  .github/workflows/tests.yml
  .gitignore
  README.md
  bot.py
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  setup.cfg
  setup.py
  src/heckbot/__init__.py
  src/heckbot/adaptor/__init__.py
  src/heckbot/adaptor/config_json_adaptor.py
  src/heckbot/adaptor/dynamo_table_adaptor.py
  src/heckbot/cogs/__init__.py
  src/heckbot/cogs/config.py
  src/heckbot/cogs/events.py
  src/heckbot/cogs/gif.py
  src/heckbot/cogs/moderation.py
  src/heckbot/cogs/poll.py
  src/heckbot/cogs/react.py
  src/heckbot/py.typed
  src/heckbot/service/__init__.py
  src/heckbot/service/config_service.py
  src/heckbot/service/react_service.py
  src/heckbot/service/roll_service.py
  src/heckbot/types/__init__.py
  src/heckbot/types/constants.py
  src/heckbot/types/types.py
  src/heckbot/utils/__init__.py
  src/heckbot/utils/chatutils.py
  src/types/typevars.py
  tests/__init__.py
  tests/conftest.py
  tests/integration/test_dpytest.py
  tests/pytest.ini
  tests/unit/test_dynamo_table_adaptor.py
  tox.ini
Labels: testing

#53 Improve typing and type safety
  bot.py
  pyproject.toml
  src/heckbot/adaptor/config_adaptor.py
  src/heckbot/adaptor/dynamo_table_adaptor.py
  src/heckbot/cogs/config.py
  src/heckbot/cogs/events.py
  src/heckbot/cogs/gif.py
  src/heckbot/cogs/moderation.py
  src/heckbot/cogs/poll.py
  src/heckbot/cogs/react.py
Labels: documentation, enhancement

#50 Add poll close function
  .gitignore
  bot.py
  requirements_dev.txt
  src/heckbot/adapter/__init__.py
  src/heckbot/adapter/config_adapter.py
  src/heckbot/adapter/reaction_table_adapter.py
  src/heckbot/cogs/config.py
  src/heckbot/cogs/events.py
  src/heckbot/cogs/gif.py
  src/heckbot/cogs/moderation.py
  src/heckbot/cogs/poll.py
  src/heckbot/cogs/react.py
  src/heckbot/types/constants.py
Labels: enhancement

#69 Replace ospath logic with pathlib
  .gitignore
  bot.py
  tests/conftest.py
Labels: enhancement

#34 Automatically responds to messages
  .gitignore
  bot.py
  src/heckbot/adapter/message_table_adapter.py
  src/heckbot/cogs/message.py
  src/heckbot/cogs/react.py
Labels: enhancement

#75 Add type safety checks and msgdel command
  src/heckbot/adapter/message_table_adapter.py
  src/heckbot/adapter/reaction_table_adapter.py
  src/heckbot/cogs/message.py
  src/heckbot/cogs/react.py
Labels: enhancement
